// Nigerian universities, polytechnics, colleges of education and similar
// schools, for the school field's suggestions. Anything else can still be
// typed. The same list as the Sajal app's nigerian_institutions.dart,
// gathered on 2026-10-01 from the NUC, NBTE and NCCE lists and Wikipedia.
export const INSTITUTIONS: readonly string[] = [
  "A.D. Rufa'i College for Islamic and Legal Studies, Misau",
  "AB Naibi College of Nursing Sciences, Lau",
  "Abdu Gusau Polytechnic, Talata Mafara",
  "Abdulfattah Durojaiye University, Abeokuta Ogun State",
  "AbdulKadir Kure University, Minna Niger State",
  "Abdulrasaq Abubakar Toyin University, Oke-Ogba, Ganmo, Ilorin, Kwara State",
  "Abdulsalam Abubakar University of Agriculture and Climate Action, Mokwa, Niger State",
  "Abia State College of Health Technology, Aba",
  "Abia State Polytechnic, Aba",
  "Abia State University, Uturu",
  "Abraham Adesanya Polytechnic, Ijebu Igbo",
  "Abubakar Garba Zagada-Zagada College of Education, Bajoga",
  "Abubakar Tafawa Balewa University, Bauchi",
  "Abubakar Tatari Ali Polytechnic, Bauchi",
  "ABUTH School of Health Records Administration & Biostatistics, Zaria",
  "Achievers University, Owo",
  "Adamawa State College of Education, Hong",
  "Adamawa State Polytechnic, Yola",
  "Adamawa State University Mubi",
  "Adamu Augie College of Education, Argungu",
  "Adamu Tafawa Balewa College of Education, Kangere",
  "Adeche Momoh University, Igarra, Edo State",
  "Adecom College of Business Administration and Management Studies, Ibadan",
  "Adekunle Ajasin University, Akungba",
  "Adeleke University, Ede",
  "Adeniran Ogunsanya College of Education, Oto-Ijanikin",
  "Adeseun Ogundoyin Polytechnic",
  "Adeshina College of Education, Share",
  "Adeyemi College of Education, Ondo",
  "Adeyemi Federal University of Education, Ondo",
  "Admiralty University Ibusa, Delta State",
  "Afe Babalola University, Ado-Ekiti, Ekiti State",
  "African Aviation and Aerospace University",
  "African Church College of Education, Ifako-Ijaye",
  "African Thinkers Community of Inquiry College of Education, Enugu",
  "African University of Economics, FCT, Abuja",
  "African University of Science and Technology, Abuja",
  "Ahmadu Bello University, Zaria",
  "Ahman Pategi University, Kwara State",
  "Air Force Institute of Technology (AFIT), Airforce Base, Kaduna",
  "Air Force Institute of Technology, Kaduna",
  "Ajayi Crowther University, Ibadan",
  "Ajayi Polytechnic, Ara-Ekiti",
  "Ajayi Polytechnic, Ikere",
  "AJETUNMOBI College of Education Irra, IRAA",
  "Akanu Ibiam Federal Polytechnic, Unwana",
  "Akawe Torkula Polytechnic, Makurdi",
  "Akperan Orshi College of Agriculture, Yandev",
  "Akwa Ibom State College of Arts & Science, Nung Ukim",
  "Akwa Ibom State College of Arts and Science, Ikono",
  "Akwa Ibom State College of Education, Afaha-Nsit",
  "Akwa Ibom State Polytechnic, Ikot Ekpene",
  "Akwa Ibom State Polytechnic, Ikot Osurua",
  "Akwa Ibom State University, Ikot Akpaden",
  "Al-Ansar University, Maiduguri, Borno",
  "Al-Bayan University, Ankpa, Kogi State",
  "Al-Hikma College of Education, Ankpa",
  "Al-Hikma Polytechnic, Karu",
  "Al-Hikmah University, Ilorin",
  "Al-Ibadan College of Education, Ibadan",
  "Al-Istiqama University, Sumaila, Kano State",
  "Al-Muhibbah Open University, Abuja",
  "Al-Qalam University, Katsina",
  "Aletheia University, Ago-Iwoye Ogun State",
  "Alex Ekwueme University, Ndufu-Alike, Ebonyi State",
  "Aliko Dangote University of Science & Technology, Wudil",
  "Allover Central Polytechnic, Sango-Ota",
  "Alvan Ikoku Federal College of Education, Owerri",
  "Alvan Ikoku Federal University of Education, Owerri, Imo State",
  "Amadeus University, Amizi, Abia State",
  "Amaj University, Kwali, Abuja",
  "Ambrose Alli University, Ekpoma",
  "Ameer Shehu Idris College of Advanced Studies, Zaria",
  "American Open University, Abeokuta, Ogun State",
  "American Polytechnic, Wasimi",
  "American University of Nigeria, Yola",
  "Aminu Dabo College of Health Sciences and Technology, kano",
  "Aminu Kano College of Islamic and Legal Studies, Kano",
  "Aminu Saleh College of Education, Azare",
  "Anambra State College of Health Technology, Obosi",
  "Anambra State Polytechnic, Awka North",
  "Anambra State Polytechnic, Mgbakwu",
  "Anan University, Kwall, Plateau State",
  "Anchor University Ayobo Lagos State",
  "Angel Crown College of Education, Gidan Daya",
  "Annur College of Education, Kano",
  "Ansar-Ud-Deen College of Education, Isolo",
  "Apa College of Education, Aidogodo",
  "Arthur Javis University Akpoyubo Cross river State",
  "Ashi Polytechnic, Anyiin, Logo LGA, Benue State",
  "Ashi Polytechnic, Anyin",
  "Assanusiyah College of Education, Odeomu",
  "Atiba University Oyo",
  "Atiku Abubakar College of Legal and Islamic Studies, Nguru",
  "Auchi Polytechnic, Auchi",
  "Audu Bako College of Agriculture, Danbatta",
  "Augustine University",
  "Ave Maria University, Piyanko, Nasarawa State",
  "Awori District College of Education, Sango-Ota",
  "Azione Verde University, Amaigbo, Imo State",
  "Azman University, Kano State",
  "Baba Ahmed University, Kano State",
  "Babcock University, Ilishan-Remo",
  "Bamidele Olumilua University of Science and Technology Ikere, Ekiti State",
  "Bartholomew College of Health Technology, Shao, Kwara State",
  "Bauchi Institute for Arabic and Islamic Studies, Bauchi",
  "Bauchi State College of Agriculture, Bauchi",
  "Bauchi State University, Gadau",
  "Bayelsa Medical University",
  "Bayelsa State College of Health Technology, Otuogidi, Bayelsa State",
  "Bayelsa State Polytechnic, Ekeremor",
  "Bayelsa State Polytechnic, Elebele",
  "Bayero University, Kano",
  "Bayo Tijani College of Education, Ikotun",
  "Baze University",
  "Bellarks Polytechnic, Kwale",
  "Bells University of Technology, Otta",
  "Benson Idahosa University, Benin City",
  "Benue State Polytechnic, Ugbokolo",
  "Benue State University of Agriculture Science and Technology, Ihugh",
  "Best Legacy College of Education, Ogbomoso",
  "Best Solution Polytechnic, Akure",
  "Bethel College of Education, Ijare",
  "Biga College of Education, Sokoto",
  "Bill and Melinda Gates College of Health Technology, Ningi",
  "Bilyaminu Othman College of Education, Dass",
  "Bingham University, New Karu",
  "Binyaminu Usman Polytechnic, Hadejia",
  "Bogoro College of Education, Bogoro",
  "Bolmor Polytechnic, Ibadan",
  "Bowen University, Iwo",
  "Brainfill Polytechnic, Ikot-Ekpene",
  "Bridget University Mbaise, Okirika-Nweke, Imo State",
  "British Canadian University, Obufu Cross River State",
  "British Transatlantic Polytechnic, Akure",
  "Caleb University, Lagos",
  "Calvary Polytechnic, Ika North East",
  "Calvary Polytechnic, Owa-Oyibu",
  "Calvin Foundation College of Education, Naka",
  "Canadian University of Nigeria, Abuja",
  "Capital City University, Kano State",
  "Captain Elechi Amadi Polytechnic (formerly Port Harcourt Polytechnic), Rumuola",
  "Caritas University, Enugu",
  "Charkin Maritime Academy, Port Harcourt, Rivers State",
  "Chrisland University",
  "Christopher University Mowe",
  "Chukwuemeka Odumegwu Ojukwu University, Uli",
  "Citi Polytechnic, Bwari",
  "Citi Polytechnic, Dutsen-Dawaki, Abuja",
  "City College of Education, Mararaba",
  "City University Abuja",
  "Claretian University of Nigeria, Nekede, Imo State",
  "Clifford University Owerrinta Abia State",
  "Coal City University Enugu State",
  "Coastal Polytechnic, Badagry",
  "Coastal Polytechnic, Lagos",
  "College of Administration and Business Studies, Potiskum",
  "College of Administration, Management and Technology, Potiskum",
  "College of Agriculture & Animal Science, Bakura",
  "College of Agriculture and Animal Science, DAC-ABU, Mando, Kaduna",
  "College of Agriculture, DAC-ABU, Kabba",
  "College of Agriculture, Jalingo",
  "College of Agriculture, Science and Technology, Gujba",
  "College of Agriculture, Science and Technology, Lafia",
  "College of Agriculture, Zuru",
  "College of Arabic and Islamic Legal Studies, Ilorin, Kwara State",
  "College of Business and Management Studies, Konduga",
  "College of Education and Legal Studies, Nguru",
  "College of Education, Agbor",
  "College of Education, Akwanga",
  "College of Education, Billiri",
  "College of Education, Darazo",
  "College of Education, Ekiadolor",
  "College of Education, Ero, Akure",
  "College of Education, Gindiri",
  "College of Education, Ikere-Ekiti",
  "College of Education, Ilemona",
  "College of Education, Katsina-Ala",
  "College of Education, Kura",
  "College of Education, Moro, Ife-North",
  "College of Education, Nsukka",
  "College of Education, Oju",
  "College of Education, Waka-Biu",
  "College of Education, Warri",
  "College of Education, Zing",
  "College of Health Science and Technology, Idah, Kogi State",
  "College of Health Science and Technology, Ile-Ife, Osun State",
  "College of Health Technology, Zawan",
  "College of Nursing and Midwifery, Gombe, Gombe State",
  "College of Petroleum and Energy Studies, Kaduna State",
  "College of Sharia and Arabic Studies, Bauchi",
  "Confluence University of Science and Technology Osara, Kogi",
  "Cornerstone College of Education, Ikeja",
  "Corona College of Education, Lekki",
  "Cosmopolitan University Abuja",
  "Covenant College of Education, Aba",
  "Covenant Polytechnic, Aba",
  "Covenant University Ota",
  "Crawford University Igbesa",
  "Crescent University",
  "Crestfield College of Education, Erin-Osun",
  "Cross River Institute of Technology and Management, Ugep",
  "Cross River State College of Education, Akamkpa",
  "Cross River State College of Health Technology, Calabar",
  "Cross River University of Education and Entrepreneurship, Akampa, Cross River State",
  "Crown Polytechnic, Ado-Ekiti",
  "D.S. Adegbenro ICT Polytechnic, Itori- Ewekoro",
  "Da'awa College of Education, Bauchi",
  "Daboss Polytechnic, Idominasi",
  "David Nweze Umahi Federal University of Medical Sciences, Uburu",
  "Delar College of Education, Ibadan",
  "Delta State College of Education, Mosogar",
  "Delta State Maritime Polytechnic, Burutu",
  "Delta State Polytechnic, Ogwashi-Uku",
  "Delta State Polytechnic, Otefe-Oghara",
  "Delta State Polytechnic, Ozoro",
  "Delta State School of Health Technology, Ugheli",
  "Delta State School of Marine Technology, Burutu",
  "Delta State University Abraka",
  "Delta University of Science and Technology, Ozoro",
  "Dennis Osadebe University, Asaba",
  "Diamond College of Education, Aba",
  "Distinct Polytechnic, Ekosin",
  "Dominican University Ibadan Oyo State",
  "Dominion University Ibadan, Oyo State",
  "Dorben Polytechnic, Bwari, Abuja",
  "Eastern Polytechnic, Port Harcourt",
  "Ebenezer College of Education, Amangwu-Edda",
  "Ebonyi State College of Education, Ikwo",
  "Ebonyi State University of ICT, Science and Technology, Oferekpe, Ebonyi State",
  "Ebonyi State University, Abakaliki",
  "ECWA College of Education, Igbaja",
  "ECWA College of Education, Jos",
  "ED-John School of Management, Ikorodu",
  "Edo State College of Agriculture, Iguoriakhi",
  "Edo State College of Education, Igueben",
  "Edo State Polytechnic, Usen",
  "Edo State University, Iyamho",
  "Edusoko University, Bida, Niger State",
  "Edward Olaseni Polytechnic, Akoko",
  "Edwin Clark University, Kaigbodo",
  "Ekiti City Polytechnic, Umuooke",
  "Ekiti State College of Agriculture and Technology, Ado-Ekiti",
  "Ekiti State College of Agriculture and Technology, Isan-Ekiti",
  "Ekiti State College of Health Sciences and Technology, Ijero Ekiti",
  "Ekiti State University",
  "Eko College of Management and Technology(Ekocity), Ikotun",
  "Eko University of Medical and Health Sciences Ijanikin, Lagos",
  "El-Amin University, Minna, Niger State",
  "El-thomp Polytechnic, Abak",
  "Elder Oyama Memorial College of Education, Ofat",
  "Elizabeth Memorial College of Education, Nsukka",
  "Elizade University, Ilara-Mokin",
  "Elrazi Medical University Yargaya University, Kano State",
  "Emanuel Alayande University of Education Oyo",
  "Emirates College of Health Sciences and Technology, Kabuga, Kano",
  "Emmanuel Alayande College of Education, Oyo",
  "Emmanuel Ebije Ikwue College of Education, Otukpo",
  "Enugu State College of Education (Technical), Enugu",
  "Enugu State Polytechnic, Iwollo",
  "Enugu State University of Science and Technology, Enugu",
  "Enville Institute of Management and Technology, Iganke",
  "Eranova University, Abuja",
  "European University of Nigeria, Duboyi, FCT",
  "Euston University, Abakaliki, Ebonyi State",
  "Evangel University, Akaeze",
  "FCT College of Education, Zuba",
  "Federal College of Agricultural Produce Technology, Kano",
  "Federal College of Agriculture, Akure",
  "Federal College of Agriculture, Ishiagu",
  "Federal College of Agriculture, Moor Plantation, Ibadan",
  "Federal College of Animal Health & Production Technology, Ibadan",
  "Federal College of Animal Health & Production Technology, Vom",
  "Federal College of Education (Special), Oyo",
  "Federal College of Education (Technical), Akoka",
  "Federal College of Education (Technical), Asaba",
  "Federal College of Education (Technical), Bichi",
  "Federal College of Education (Technical), Gombe",
  "Federal College of Education (Technical), Gusau",
  "Federal College of Education (Technical), Omoku",
  "Federal College of Education (Technical), Potiskum",
  "Federal College of Education (Technical), Umunze",
  "Federal College of Education, Abeokuta",
  "Federal College of Education, Eha-Amufu",
  "Federal College of Education, Ididep",
  "Federal College of Education, Iwo",
  "Federal College of Education, Kano",
  "Federal College of Education, Katsina",
  "Federal College of Education, Kontagora",
  "Federal College of Education, Obudu",
  "Federal College of Education, Okene",
  "Federal College of Education, Pankshin",
  "Federal College of Education, Yola",
  "Federal College of Education, Zaria",
  "Federal College of Fisheries & Marine Technology, Victoria Island, Lagos",
  "Federal College of Forestry Mechanisation, Afaka",
  "Federal College of Forestry, Ibadan",
  "Federal College of Forestry, Jos",
  "Federal College of Freshwater Fisheries Technology, Baga",
  "Federal College of Freshwater Fisheries Technology, New Bussa",
  "Federal College of Horticultural Technology, Dadin Kowa",
  "Federal College of Land Resources Technology, Kuru, Jos",
  "Federal College of Land Resources Technology, Owerri",
  "Federal College of Orthopaedic Technology, NOH, Igbobi, Lagos",
  "Federal College of Wildlife Management, New Bussa",
  "Federal Cooperative College, Ibadan",
  "Federal Cooperative College, Kaduna",
  "Federal Cooperative College, Oji-River",
  "Federal Polytechnic Ayede",
  "Federal Polytechnic Daura",
  "Federal Polytechnic Kabo",
  "Federal Polytechnic Kaltungo",
  "Federal Polytechnic Monguno",
  "Federal Polytechnic Ngodo Isuochi, Aba North",
  "Federal Polytechnic Nyak Shendam",
  "Federal Polytechnic of Oil and Gas, Bonny",
  "Federal Polytechnic Ohodo",
  "Federal Polytechnic Orogun",
  "Federal Polytechnic Ugep",
  "Federal Polytechnic Wannune, Tarka",
  "Federal Polytechnic, Ado-Ekiti",
  "Federal Polytechnic, Bali",
  "Federal Polytechnic, Bauchi",
  "Federal Polytechnic, Bida",
  "Federal Polytechnic, Damaturu",
  "Federal Polytechnic, Ede",
  "Federal Polytechnic, Ekowe",
  "Federal Polytechnic, Idah",
  "Federal Polytechnic, Ilaro",
  "Federal Polytechnic, Ile-Oluji",
  "Federal Polytechnic, Kaura-Namoda",
  "Federal Polytechnic, Mubi",
  "Federal Polytechnic, Nasarawa",
  "Federal Polytechnic, Nekede, Owerri",
  "Federal Polytechnic, Offa",
  "Federal Polytechnic, Oko",
  "Federal Polytechnic, Ukana",
  "Federal School of Dental Technology & Therapy, Enugu",
  "Federal School of Social Works, Emene, Enugu",
  "Federal School of Statistics, Ibadan",
  "Federal School of Statistics, Manchok",
  "Federal School of Surveying, Oyo",
  "Federal University Gashua, Yobe",
  "Federal University of Agriculture and Developmental Studies, Iragbuji, Osun State",
  "Federal University of Agriculture and Technology Obio-Akpa Akwa Ibom State",
  "Federal University of Agriculture and Technology Okeho, Oyo State",
  "Federal University of Agriculture Bassam-Biri, Bayelsa",
  "Federal University of Agriculture, Abeokuta",
  "Federal University of Agriculture, Mubi",
  "Federal University of Agriculture, Zuru, Kebbi State",
  "Federal University of Allied Health Sciences, Enugu",
  "Federal University of Applied Sciences, Kachia, Kaduna State",
  "Federal University of Education Kontagora, Niger State",
  "Federal University of Education Pankshin, Plateau State",
  "Federal University of Education, Zaria, Kaduna State",
  "Federal University of Environment and Technology, Tai Town, Ogoniland, Rivers State",
  "Federal University of Health Science and Technology, Tsafe",
  "Federal University of Health Sciences Kwale, Delta State",
  "Federal University of Health Sciences, Azare, Bauchi State",
  "Federal University of Health Sciences, Ila Orangun, Osun State",
  "Federal University of Health Sciences, Katsina",
  "Federal University of Health Sciences, Otukpo, Benue State",
  "Federal University of Medicine and Medical Sciences, Abeokuta",
  "Federal University of Petroleum Resources, Effurun",
  "Federal University of Science and Technology, Epe",
  "Federal University of Science and Technology, Kabo, Kano",
  "Federal University of Technology and Environmental Studies, Iyin-Ekiti, Ekiti State",
  "Federal University of Technology, Akure",
  "Federal University of Technology, Babura, Jigawa State",
  "Federal University of Technology, Ikot Abasi, Akwa Ibom State",
  "Federal University of Technology, Minna",
  "Federal University of Technology, Owerri",
  "Federal University of Transportation Daura, Katsina",
  "Federal University, Birnin Kebbi",
  "Federal University, Dutse, Jigawa State",
  "Federal University, Dutsin-Ma, Katsina",
  "Federal University, Gusau Zamfara",
  "Federal University, Kashere, Gombe State",
  "Federal University, Lafia, Nasarawa State",
  "Federal University, Lokoja, Kogi State",
  "Federal University, Otuoke, Bayelsa",
  "Federal University, Oye-Ekiti, Ekiti State",
  "Federal University, Wukari, Taraba State",
  "FESTMED College of Education, Ajowa-Akoko",
  "Fidei Polytechnic, Gboko",
  "First City Polytechnic, Abeokuta",
  "First Technical University Ibadan",
  "Foundation Polytechnic, Ikot-Ekpene",
  "Fountain University, Osogbo",
  "Franco British International University, Kaduna State",
  "Gateway Polytechnic, Saapade",
  "Gboko College of Education, Gboko",
  "Gboko Polytechnic, Gboko",
  "Gerar University of Medical Science Imope Ijebu, Ogun State",
  "Global College of Education, Bukuru, Jos",
  "Global Polytechnic, Akure",
  "Global Polytechnic, Benin",
  "Glorious Vision University, Ogwa, Edo State",
  "Gloryland Polytechnic, Ankpa",
  "Godday Erewa University, Sapele, Delta State",
  "Godfrey Okoye University, Ugwuomu-Nike, Enugu State",
  "Gombe State College of Health Science & Technology, Kaltungo",
  "Gombe State Polytechnic, Bajoga",
  "Gombe State University, Gombe",
  "Good Shepherd College of Education, Alakuko",
  "Gozie Anyachebelu Oragram Polytechnic, Oraukwu",
  "Grace Polytechnic, Surulere, Lagos",
  "Gracelane Polytechnic, Offa, Kwara State",
  "Greenfield University, Kaduna",
  "Greenland University, Jalingo, Taraba State",
  "Gregory University, Uturu",
  "Grundtvig Polytechnic, Oba, Anambra State",
  "Hallmark University, Ijebi Itele, Ogun",
  "Hamzainab College of Education, Osogbo",
  "Harry Pass Polytechnic, Mkar",
  "Harry Pass Polytechnic, Usen Mkar, Gboko",
  "Harvard Polytechnic, Ilorin",
  "Harvarde College of Business and Management Studies, Abeokuta",
  "Hassan Usman Katsina Polytechnic, Katsina",
  "Havard Wilson College of Education, Aba",
  "Havilla University, Nde-Ikom, Cross River State",
  "Hensard University, Toru-Orua, Sagbama, Bayelsa State",
  "Heritage Polytechnic, Eket",
  "Heritage Polytechnic, Ikot-Udota, Eket",
  "Hezekiah University, Umudi",
  "High Flyers University, Ikere-Ekiti, Ekiti State",
  "Hill College of Education, Gwanje, Akwanga",
  "Hillside University of Science and Technology, Okemisi, Ekiti State",
  "Hope and Anchor College of Education, Suleja",
  "Hope Polytechnic, Ikono",
  "Huda University, Gusau, Zamfara State",
  "Hussaini Adamu Federal Polytechnic, Kazaure",
  "Ibadan City Polytechnic, Ibadan",
  "Ibom Metropolitan Polytechnic, Atan Offot",
  "Ibrahim Badamasi Babangida University, Lapai",
  "ICON-Universal Polytechnic, Osogbo",
  "Iconic Open University, Sokoto State",
  "Igbajo Polytechnic, Igbajo",
  "Igbinedion University Okada",
  "Ignatius Ajuru University of Education, Rumuolumeni",
  "Iheachukwu Madubuike Institute of Technology, Isuochi",
  "Iheachukwu Madubuike Institute of Technology, Umunneochi",
  "Ilori College of Education, Ede",
  "Imam Hamzat College of Education, Ilorin",
  "Imam Saidu College of Education, Funtua",
  "Imo State College of Education (Technical), Ihitte/Uboma",
  "Imo State College of Nursing & Health Sciences, Amaigbo",
  "Imo State Polytechnic, Oru East",
  "Imo State Polytechnic, Umuagwo, Ohaji",
  "Imo State University, Owerri",
  "Inspire Polytechnic, Yaba",
  "Institute of Administration, ABU, Zaria",
  "Institute of Ecumenical Education, Enugu",
  "Institute of Health Technology, University Teaching Hospital, Benin",
  "Institute of Management and Technology, Enugu",
  "Institute Of Technology And Management, Ugep",
  "Intercontinental College of Technology, Makurdi",
  "Interlink Polytechnic, Ijebu-Jesa",
  "Ipere College of Education, Agyaragu",
  "Isa Kaita College of Education, Dutsin-Ma",
  "Isa Mustapha Agwai Polytechnic, Lafia",
  "Isaac Balami University of Aeronautics and Management, Lagos State",
  "Isaac Jasper Boro College of Education, Sagbama",
  "Islamic College of Education, Potiskum",
  "Iwo City Polytechnic, Iwo",
  "James Hope University, Lagos, Lagos State",
  "JEFAP University, Suleja, Niger State",
  "Jewel University, Gombe state",
  "JIBWIS College of Education, Gombe",
  "JIBWIS College of Education, Jama'are",
  "Jigawa State College of Education and Legal Studies, Ringim",
  "Jigawa State College of Education, Gumel",
  "Jigawa State Institute of Information Technology, Kazaure",
  "Jigawa State Polytechnic, Dutse",
  "Jigawa State University of Medical and Allied Health Sciences, Majia",
  "Jimoh Babalola University, Ilorin, Kwara State",
  "Joseph Ayo Babalola University, Ikeji-Arakeji",
  "Joseph Sarwuan Tarka University, Makurdi",
  "Kaduna Polytechnic, Kaduna",
  "Kaduna State College of Education, Gidan Waya",
  "Kaduna State University, Kaduna",
  "Kalac Crystal Polytechnic, Lekki",
  "Kano State College of Education and Preliminary Studies, Kano",
  "Kano State College of Health Sciences and Technology, Kano",
  "Kano State Polytechnic, Kano",
  "Karl-Kumm University, Vom, Plateau State",
  "Kashim Ibrahim College of Education, Maiduguri",
  "Kashim Ibrahim University (formerly Borno State University), Maiduguri",
  "Katsina Institute of Technology and Management",
  "Kebbi State Polytechnic, Dakingari",
  "Kebbi State University of Science and Technology, Aliero",
  "Kenule Beeson Saro-Wiwa Polytechnic, Bori",
  "Kevin Eze University, Mgbowo, Enugu State",
  "Khalifa Isiyaku Rabiu University, Kano",
  "Kings Polytechnic, Ubiaja",
  "Kings University, Ode Omu",
  "Kingsley Ozumba Mbadiwe University Ogboko, Imo State",
  "Kinsey College of Education, Ilorin",
  "Kogi East College of Education, Egbeche",
  "Kogi State College of Education (Technical), Kabba",
  "Kogi State College of Education, Ankpa",
  "Kogi State Polytechnic, Lokoja",
  "Kogi State University, Kabba",
  "Kola Daisi University Ibadan, Oyo State",
  "Kwara State College of Education (Technical), Lafiagi",
  "Kwara State College of Education, Ilorin",
  "Kwara State College of Education, Oro",
  "Kwara State College of Health Technology, Offa",
  "Kwara State Polytechnic, Ilorin",
  "Kwara State University of Education, Ilorin, Kwara State",
  "Kwara State University, Ilorin",
  "Kwararafa College of Education, Otukpo",
  "Kwararafa University, Wukari",
  "Ladoke Akintola University of Technology, Ogbomoso",
  "Lagos City Polytechnic, Ikeja",
  "Lagos State College of Health Technology, Yaba",
  "Lagos State Polytechnic, Ikorodu",
  "Lagos State University of Education, Ijanikin",
  "Lagos State University of Science and Technology Ikorodu",
  "Lagos State University, Ojo",
  "Landmark Polytechnic, Aiyetoro",
  "Landmark Polytechnic, Ayetoro",
  "Landmark University, Omu-Aran",
  "Lapo Institute of Microfinance & Enterprise Development, Benin",
  "Lead City University, Ibadan",
  "Leadership University, Abuja, FCT",
  "Legacy University, Okija Anambra State",
  "Lens Polytechnic, Offa",
  "Lens University, Ilemona, Kwara State",
  "Lessel College of Education, Ushongo",
  "Lifegate College of Education, Asa",
  "Lighthouse Polytechnic, Evbuobanosa",
  "Lighthouse Polytechnic, Orhionmwon",
  "Lighthouse University, Evbobanosa, Edo State",
  "Loam Polytechnic, Ikono",
  "Lux Mundi University Umuahia, Abia State",
  "Madonna College of Health Technology, Umuahia South",
  "Madonna University, Okija",
  "Maduka University, Ekwegbe, Enugu State",
  "Mai-Idris Alooma Polytechnic, Geidam",
  "Maranatha University, Lagos",
  "Margaret Lawrence University, Umunede, Delta State",
  "Maria Assumpta University Owerri, Imo State",
  "Marist Polytechnic, Enugu",
  "Marist Polytechnic, Umuchigbo-Ije, Nike, Emene, Enugu",
  "Maritime Academy, Oron",
  "Maryam Abacha American University of Nigeria, Kano State",
  "Mater Dei Polytechnic, Egwuoba",
  "Mater Dei Polytechnic, Ugwuoba",
  "MCF College of Education, Agbarha-Otor",
  "McPherson University, Seriki Sotayo, Ajebo",
  "Meadow Hall College of Education, Lekki",
  "Mercy Medical University, Iwo, Ogun State",
  "Metallurgical Training Institute, Onitsha",
  "Meteorological Institute of Science and Technology, Katsina, Katsina State",
  "Metro College of Education, Adogi-Lafia",
  "Mewar International University, Masaka, Nasarawa State",
  "Michael and Cecilia Ibru University",
  "Michael Imodu National Institute for Labour Studies, Ilorin",
  "Michael Okpara University of Agriculture, Umudike",
  "Michael Otedola College of Primary Education, Noforija-Epe",
  "Millenium Crest University, Ikare Akoko, Ondo State",
  "Millennium College of Health Technology, Akure",
  "Minaret University, Ikirun, Osun State",
  "Miva Open University, Abuja FCT",
  "Modibbo Adama University of Technology, Yola",
  "Mohamet Lawan College of Agriculture, Maiduguri",
  "Mohammed Goni College of Legal and Islamic Studies, Maiduguri",
  "Moje College of Education, Erin-Ile",
  "Monarch University, Iyesi-Ota, Ogun State",
  "Montgomery Polytechnic, Ikere",
  "Moshood Abiola Polytechnic, Abeokuta",
  "Moshood Abiola University of Science and Technology Abeokuta",
  "Mountain Top University",
  "Mudiame University, Irrua, Edo State",
  "Muftau Olanihun College of Education, Ibadan",
  "Muhammad Kamalud University Kwara",
  "Muhyideen College of Education, Ilorin",
  "Murtadha College of Education, Olodo, Ibadan",
  "Mustibrah Polytechnic, Tudun Fulani",
  "NACABS Polytechnic, Akwanga",
  "Nana Aishat Memorial College of Education, Ilorin",
  "Nasarawa State College of Agriculture and Technology, Lafia",
  "Nasarawa State College of Health Science and Technology, Keffi",
  "Nasarawa State University Keffi",
  "Nation Builders Polytechnic, Asaba",
  "National Institute for Legislative and Democratic Studies, Abuja",
  "National Institute for Nigerian Languages, Aba",
  "National Institute of Construction, Technology and Management, Uromi",
  "National Open University of Nigeria, Abuja",
  "National Teachers' Institute, Kaduna",
  "National University of Science and Technology, Abuja",
  "National Water Resources Institute, Mando, Kaduna",
  "Nazareth College of Health Science and Technology",
  "New City University, Ayetoro, Ogun State",
  "Newgate College of Health Technology, Minna",
  "Newgate University, Minna, Niger State",
  "Newland Polytechnic, Ilorin",
  "Niger Delta University Yenagoa",
  "Niger State College of Agriculture, Mokwa",
  "Niger State College of Education, Minna",
  "Niger State Polytechnic, Zungeru",
  "Nigeria Police Academy Wudil",
  "Nigerian Army College of Environmental Science and Technology (NACEST), Makurdi",
  "Nigerian Army College of Nursing, Yaba, Lagos",
  "Nigerian Army School of Education, Ilorin",
  "Nigerian Army School of Finance and Administration, Apapa, Lagos",
  "Nigerian Army School of Signals, Apapa, Lagos",
  "Nigerian Army University Biu",
  "Nigerian British University, Asa, Abia State",
  "Nigerian College of Aviation Technology (NCAT), Zaria",
  "Nigerian Defence Academy Kaduna",
  "Nigerian Institute of Journalism, Ikeja, Lagos",
  "Nigerian Institute of Leather Sciences and Technology, Samaru, Zaria",
  "Nigerian Maritime University Okerenkoko, Delta State",
  "Nigerian Navy Engineering College, Sapele",
  "Nigerian Navy Finance and Logistics College, Owerrinta, Abia State",
  "Nigerian Navy School of Health Sciences, Offa",
  "Nigerian University of Technology and Management, Apapa, Lagos State",
  "Nile University of Nigeria, Abuja",
  "NKST College of Health Technology, Mkar, Gboko",
  "Nnamdi Azikiwe University, Awka",
  "NOGAK Polytechnic, Ikom",
  "North Eastern University, Gombe",
  "Northwest University Kano",
  "NorthWest University Sokoto State",
  "Nosakhare College of Education, Benin City",
  "Novelty Polytechnic, Kishi",
  "Novena University, Ogume",
  "Nuhu Bamalli Polytechnic, Zaria",
  "Nwafor Orizu College of Education, Nsugbe",
  "Obafemi Awolowo University, Ile-Ife",
  "Obong University, Obong Ntak",
  "Odaji Agbo Polytechnic, Ayeko-Yala",
  "Oduduwa Polytechnic, Idimu",
  "Oduduwa University, Ipetumodu, Osun State",
  "Ogun State College of Health Technology, Ijebu, Ilese",
  "Ogun State Institute of Technology, Igbesa",
  "Ogun State Polytechnic, Ipokia",
  "Ojaja University Eiyenkorin, Kwara State",
  "Olabisi Onabanjo University, Ago Iwoye",
  "Olusegun Agagu University of Science and Technology, Okitipupa",
  "Omega University Kaduna",
  "ONIT College of Education, Abagana",
  "OSISATECH College of Education, Enugu",
  "Osun State College of Education, Ila-Orangun",
  "Osun State College of Education, Ilesa",
  "Osun State College of Health Technology, Ilesa",
  "Osun State College of Technology, Esa-Oke",
  "Osun State Polytechnic, Iree",
  "Osun State University Osogbo",
  "Oswald Waller College of Education, Shendam",
  "Our Saviour Institute of Science, Agriculture & Technology (OSISATECH), Enugu",
  "Owolabi University, Oke Ila Orangun",
  "Oyo State College of Agriculture and Technology, Igbo-Ora",
  "Oyo State College of Agriculture and Technology, Igboora",
  "Oyo State College of Health Sciences and Technology, Eleyele, Ibadan",
  "PAMO University of Medical Sciences, Port Harcourt",
  "Pan African College of Education, Offa",
  "Pan-Atlantic University, Lagos",
  "Paramount Polytechnic, Ejigbo",
  "Paul University, Awka, Anambra State",
  "Peace College of Education, Ankpa",
  "Peaceland College of Education, Enugu",
  "PeaceLand University, Enugu State",
  "Peacock College of Education, Jalingo",
  "Pearl University, Calabar, Cross river",
  "Peter University, Achina-Onneh Anambra State",
  "Petroleum Training Institute, Effurun",
  "Philomath University, Kuje, Abuja",
  "Phoenix University, Agwada, Nasarawa State",
  "Piaget College of Education, Abeokuta",
  "Plateau State College of Agriculture, Garkawa",
  "Plateau State Polytechnic, Barkin Ladi",
  "Plateau State University Bokkos",
  "Pogil College of Health Technology, Ijebu-Ode",
  "Precious Cornerstone University, Oyo",
  "Prime Polytechnic, Ajaokuta",
  "Prime Polytechnic, Jida, Bassa, Ajaokuta",
  "Prime University, Kuje, FCT Abuja",
  "Prince Abubakar Audu University Anyigba",
  "Raindrops Institute of Management and Technology, Orsu",
  "Ramat Polytechnic, Maiduguri",
  "Raphat College of Education, Obaagun",
  "Rayhaan University, Kebbi",
  "Redeemer's University, Ede",
  "Redeemers College of Technology and Management, Mowe, Lagos",
  "Regnum Medical University, Anthony, Lagos State",
  "Renaissance University, Enugu",
  "Rev. Fr. Moses Orshio Adasu University (formerly Benue State University), Makurdi",
  "Rhema University, Obeama-Asa, Rivers State",
  "Ritman University, Ikot Ekpene, Akwa Ibom",
  "Rivers State College of Health Technology, Port Harcourt",
  "Rivers State University",
  "Ronik Polytechnic, Ejigbo, Lagos",
  "Royal City College of Education, Iyesi-Ota",
  "Royal College of Education, Ikeja",
  "Rufus Giwa Polytechnic, Owo",
  "Sa'adatu Rimi College of Education, Kumbotso",
  "SAF Polytechnic, Iseyin",
  "Saisa University of Medical Sciences and Technology, Sokoto State",
  "Salem University, Lokoja",
  "Sam Maris University, Ondo",
  "Samaru College of Agriculture, DAC-ABU, Zaria",
  "Sani Bello University, Kontagora Niger State",
  "Sarkin Yama Community College of Education, Toro",
  "School of Biomedical Engineering Technology, Luth, Idi Araba, Lagos",
  "School of Biomedical Engineering, UBTH, Benin",
  "School of Biomedical Engineering, UMTH, Maiduguri",
  "School of Health Information Management, AKTH, Kano",
  "School of Health Information Management, LUTH, Idi Araba, Lagos",
  "School of Health Information Management, NAUTH, Nnewi",
  "School of Health Information Management, OAUTH, Ile-Ife",
  "School of Health Information Management, UBTH, Benin",
  "School of Health Information Management, UCH, Ibadan",
  "School of Health Information Management, UCTH, Calabar",
  "School of Health Information Management, UDUTH, Sokoto",
  "School of Health Information Management, UITH, Ilorin",
  "School of Health Information Management, UMTH, Maiduguri",
  "School of Health Information Management, University of Uyo",
  "School of Health Information Management, UPTH, Port-Harcourt",
  "School of Health Technology, Akure",
  "School of Health Technology, Keffi, Nasarawa State",
  "School of Nursing and Midwifery, A.T.B.U.T.H. Bauchi",
  "School of Nursing Obafemi Awolowo University OAU Teaching Hospital Complex, Ile-Ife",
  "School of Nursing Wesley Guilds Hospital, OAU, Ilesa",
  "School of Orthopaedic Cast Technology, National Orthopaedic Hospital Dala, Kano",
  "School of Orthopaedic Cast Technology, National Orthopaedic Hospital, Enugu",
  "School of Orthopedic Cast Technology, UITH, Ilorin",
  "Shaka Polytechnic, Benin",
  "Shanahan University Onitsha, Anambra State",
  "Shehu Idris College of Health Sciences and Technology, Makarfi",
  "Shehu Shagari College of Education, Sokoto",
  "Shehu Shagari University of Education, Sokoto",
  "Sinai College of Education and Entrepreneurial Studies, Gboko",
  "Skyline University, Kano",
  "Sokoto State University",
  "Southern Atlantic Polytechnic, Uyo",
  "Southern Atlantic University, Uyo, Akwa Ibom State",
  "Southwestern University, Oku Owa",
  "Speedway Polytechnic, Osoba",
  "Spiritan University, Nneochi Abia State",
  "Sports University, Idumuje, Ugboko, Delta State",
  "St. Augustine College of Education, Akoka",
  "St. Mary Polytechnic, Kwamba, Suleja",
  "Stars Polytechnic, Agbedi-Atam, Ado-Oda",
  "Stars Polytechnic, Ota",
  "State University of Medical and Applied Sciences, Igbo-Eno, Enugu",
  "Steady Flow College of Education, Ikom",
  "Sule Lamido University, Kafin Hausa, Jigawa",
  "Summit University, Offa",
  "Sunnah College of Education, Bauchi",
  "Sure Foundation Polytechnic, Ikot-Akai",
  "Tai Solarin College of Education, Omu-Ijebu",
  "Tai Solarin Federal University of Education, Ijagun, Ijebu Ode",
  "Tansian University, Umunya",
  "Taraba State Polytechnic, Suntai",
  "Taraba State University of Tropical Agriculture, Science, Technology and Climate Action, Gembu",
  "Taraba State University, Jalingo",
  "Tazkiyah University, Kaduna, Kaduna State",
  "Temple Gate Polytechnic, Aba",
  "The College of Education, Lanlate",
  "The Duke Medical University, Calabar, Cross River State",
  "The Oke-Ogun Polytechnic, Saki (TOPS)",
  "The Polytechnic, Adoka",
  "The Polytechnic, Ibadan",
  "The Polytechnic, Igbo-Owu",
  "The Polytechnic, Ile-Ife",
  "The Polytechnic, Iresi (Formerly -College of Technology, Iresi)",
  "Thomas Adewumi University, Oko-Irese, Kwara State",
  "Timeon Kairos Polytechnic and Professional Institute, Lagos",
  "Tonine Iredia University of Communication, Benin City, Edo State",
  "Top-Most College of Education, Ipaja-Agbado",
  "Topfaith University, Mkpatak, Akwa Ibom State",
  "Tower Polytechnic, Ibadan",
  "Transatlantic University of Medicine and Health Sciences, Umuchukwu, Anambra State",
  "Trinity Polytechnic, Uyo",
  "Trinity University Ogun State",
  "Turath College of Education, Kano",
  "Uli College of Education, Uli",
  "Ultra Excellence Polytechnic, Ikono",
  "Uma Ukpai Polytechnic, Asaga, Ohafia",
  "Umar Bun Khatab College of Education, Tudun Nupawa, Kaduna",
  "Umar Ibn Ibrahim El-Kanemi College of Education, Bama",
  "Umar Musa Yar' Adua University Katsina",
  "Umar Suleiman College of Education, Gashua",
  "Umaru Ali Shinkafi Polytechnic, Sokoto",
  "Umaru Ali Shinkafi Polytechnic, Wamako",
  "Ummah University of Nigeria, Abuja",
  "Unique College of Management and Technology, Ikotun",
  "Unique Open University, Ojo, Lagos State",
  "United Polytechnic, Jos",
  "Unity College of Education, Aukpa-Adoka",
  "University of Abuja, Gwagwalada",
  "University of Aeronautics and Aerospace Engineering Ezza, Ebonyi State",
  "University of Africa Toru Orua, Bayelsa State",
  "University of Agriculture and Environmental Sciences Umuagwo, Imo State",
  "University of Benin",
  "University of Calabar",
  "University of Cross River State, Calabar",
  "University of Delta, Agbor",
  "University of Fortune, Igbotako, Ondo State",
  "University of Ibadan",
  "University of Ilesa, Osun State",
  "University of Ilorin",
  "University of Innovation, Science and Technology, Omuma, Imo State",
  "University of Jos",
  "University of Lagos",
  "University of Maiduguri",
  "University of Maritime Studies, Oron, Akwa Ibom State",
  "University of Medical Sciences, Ondo City, Ondo State",
  "University of Mkar, Mkar",
  "University of Nigeria, Nsukka",
  "University of Offa, Kwara State",
  "University of Port-Harcourt",
  "University of Uyo",
  "University on the Niger, Umunya, Anambra state",
  "Upland College of Education, Badagry",
  "Usmanu Danfodiyo University, Sokoto",
  "Uyo City Polytechnic, Uyo",
  "Valley View Polytechnic, Ohafia",
  "Venite University, Iloro-Ekiti, Ekiti State",
  "Veritas University, Abuja",
  "Villanova Polytechnic, Imesi-Ile (Formerly -The Polytechnic, Imesi-Ile)",
  "Villanova Polytechnic, Obokun",
  "Vineyard Polytechnic, Karu",
  "Vision University, Ikogbo, Ogun State",
  "Wavecrest College of Catering and Hospitality Management, Lagos",
  "Waziri Umaru Federal Polytechnic, Birnin-Kebbi",
  "Wellspring University, Evbuobanosa, Edo State",
  "Wesley University Ondo",
  "West Midlands Open University, Ibadan, Oyo State",
  "Western Delta University, Oghara Delta State",
  "Westland Polytechnic, Ilobu",
  "Westland University Iwo, Osun State",
  "Wigwe University, Isiokpo Rivers State",
  "Wolex Polytechnic, Iwo",
  "Yaba College of Technology, Yaba, Lagos",
  "Yewa Central College of Education, Abeokuta",
  "Yewa Central College of Education, Ayetoro",
  "Yobe State College of Agriculture Gujba",
  "Yobe State University, Damaturu",
  "Yusuf Bala Usman College of Legal and General Studies, Daura",
  "Yusuf Maitama Sule Federal University of Education, Kano",
  "Zamfara State College of Arts and Science, Gusau",
  "Zamfara State College of Education, Maru",
  "Zamfara State University",
];

// What people call a school instead, so "OAU" finds Obafemi Awolowo University.
export const INSTITUTION_ABBREVIATIONS: Readonly<Record<string, string>> = {
  "AbdulKadir Kure University, Minna Niger State": "AKUM",
  "Abia State University, Uturu": "ABSU",
  "Abubakar Tafawa Balewa University, Bauchi": "ATBU",
  "Adekunle Ajasin University, Akungba": "AAUA",
  "Adeleke University, Ede": "AUE",
  "Adeniran Ogunsanya College of Education, Oto-Ijanikin": "AOCOED",
  "Adeyemi College of Education, Ondo": "ACEONDO",
  "Adeyemi Federal University of Education, Ondo": "AFUED",
  "Admiralty University Ibusa, Delta State": "ADUN",
  "Afe Babalola University, Ado-Ekiti, Ekiti State": "ABUAD",
  "African Aviation and Aerospace University": "AAAU",
  "African University of Science and Technology, Abuja": "AUST",
  "Ahmadu Bello University, Zaria": "ABU",
  "Ahman Pategi University, Kwara State": "APU",
  "Air Force Institute of Technology, Kaduna": "AFIT",
  "Ajayi Crowther University, Ibadan": "ACU",
  "Akwa Ibom State University, Ikot Akpaden": "AKSU",
  "Al-Ansar University, Maiduguri, Borno": "AUM",
  "Al-Hikmah University, Ilorin": "AHU",
  "Al-Qalam University, Katsina": "AUK",
  "Aliko Dangote University of Science & Technology, Wudil": "ADUSTECH",
  "Alvan Ikoku Federal University of Education, Owerri, Imo State": "AIFUE",
  "Ambrose Alli University, Ekpoma": "AAU",
  "American University of Nigeria, Yola": "AUN",
  "Ave Maria University, Piyanko, Nasarawa State": "AMU",
  "Babcock University, Ilishan-Remo": "BU",
  "Bauchi State University, Gadau": "BASUG",
  "Bayelsa Medical University": "BMU",
  "Bayero University, Kano": "BUK",
  "Baze University": "BAZE",
  "Bells University of Technology, Otta": "BUT",
  "Benson Idahosa University, Benin City": "BIU",
  "Bingham University, New Karu": "BHU",
  "Bowen University, Iwo": "BOWEN",
  "Caleb University, Lagos": "CUL",
  "Chrisland University": "CLU",
  "Chukwuemeka Odumegwu Ojukwu University, Uli": "ANSU",
  "Coal City University Enugu State": "CCU",
  "Crescent University": "CUAB",
  "Delta State University Abraka": "DELSU",
  "Delta University of Science and Technology, Ozoro": "DSPZ",
  "Dominican University Ibadan Oyo State": "DUI",
  "Ebonyi State University, Abakaliki": "EBSU",
  "Edwin Clark University, Kaigbodo": "ECU",
  "Ekiti State University": "EKSU",
  "Elizade University, Ilara-Mokin": "EU",
  "Emanuel Alayande University of Education Oyo": "EAUED",
  "Emmanuel Alayande College of Education, Oyo": "EACOED",
  "Enugu State University of Science and Technology, Enugu": "ESUT",
  "Federal College of Education (Special), Oyo": "FCES",
  "Federal College of Education (Technical), Akoka": "FCE AKOKA",
  "Federal College of Education, Abeokuta": "FCE ABEOKUTA",
  "Federal College of Education, Iwo": "FCE IWO",
  "Federal Polytechnic, Ado-Ekiti": "FEDPOLYADO",
  "Federal Polytechnic, Bida": "FEDPOLYBIDA",
  "Federal Polytechnic, Ede": "FEDPOLEDE",
  "Federal Polytechnic, Ilaro": "FPI",
  "Federal Polytechnic, Ile-Oluji": "FEDPOLEL",
  "Federal Polytechnic, Nekede, Owerri": "FPNO",
  "Federal Polytechnic, Offa": "FEDPOFFA",
  "Federal University Gashua, Yobe": "FUGASHUA",
  "Federal University of Agriculture and Developmental Studies, Iragbuji, Osun State": "FUADS",
  "Federal University of Agriculture, Abeokuta": "FUNAAB",
  "Federal University of Applied Sciences, Kachia, Kaduna State": "FUASK",
  "Federal University of Education Pankshin, Plateau State": "FUEP",
  "Federal University of Education, Zaria, Kaduna State": "FUEZ",
  "Federal University of Health Sciences, Ila Orangun, Osun State": "FUHSI",
  "Federal University of Health Sciences, Otukpo, Benue State": "FUHSA",
  "Federal University of Petroleum Resources, Effurun": "FUPRE",
  "Federal University of Technology, Akure": "FUTA",
  "Federal University of Technology, Minna": "FUTMINNA",
  "Federal University of Technology, Owerri": "FUTO",
  "Federal University of Transportation Daura, Katsina": "FUTD",
  "Federal University, Oye-Ekiti, Ekiti State": "FUOYE",
  "First Technical University Ibadan": "TECH-U",
  "Fountain University, Osogbo": "FUO",
  "Godfrey Okoye University, Ugwuomu-Nike, Enugu State": "GOU",
  "Gombe State University, Gombe": "GSU",
  "Greenfield University, Kaduna": "GFU",
  "Gregory University, Uturu": "GUU",
  "Ibrahim Badamasi Babangida University, Lapai": "IBBUL",
  "Ignatius Ajuru University of Education, Rumuolumeni": "IAUE",
  "Imo State University, Owerri": "IMSU",
  "Institute of Management and Technology, Enugu": "IMT",
  "James Hope University, Lagos, Lagos State": "JHU",
  "Joseph Ayo Babalola University, Ikeji-Arakeji": "JABU",
  "Joseph Sarwuan Tarka University, Makurdi": "JOSTUM",
  "Kaduna Polytechnic, Kaduna": "KADPOLY",
  "Kaduna State University, Kaduna": "KASU",
  "Kebbi State University of Science and Technology, Aliero": "KSUSTA",
  "Kings University, Ode Omu": "KU",
  "Kingsley Ozumba Mbadiwe University Ogboko, Imo State": "KOMU",
  "Kwara State College of Education, Ilorin": "KWCOED",
  "Kwara State Polytechnic, Ilorin": "KWARAPOLY",
  "Kwara State University of Education, Ilorin, Kwara State": "KWASUED",
  "Kwara State University, Ilorin": "KWASU",
  "Ladoke Akintola University of Technology, Ogbomoso": "LAUTECH",
  "Lagos State Polytechnic, Ikorodu": "LASPOTECH",
  "Lagos State University of Education, Ijanikin": "LASUED",
  "Lagos State University of Science and Technology Ikorodu": "LASUSTECH",
  "Lagos State University, Ojo": "LASU",
  "Landmark University, Omu-Aran": "LMU",
  "Lead City University, Ibadan": "LCU",
  "McPherson University, Seriki Sotayo, Ajebo": "MCU",
  "Michael and Cecilia Ibru University": "MCIU",
  "Michael Okpara University of Agriculture, Umudike": "MOUAU",
  "Michael Otedola College of Primary Education, Noforija-Epe": "MOCPED",
  "Moshood Abiola Polytechnic, Abeokuta": "MAPOLY",
  "Mountain Top University": "MTU",
  "National Open University of Nigeria, Abuja": "NOUN",
  "Niger Delta University Yenagoa": "NDU",
  "Nigeria Police Academy Wudil": "POLAC",
  "Nigerian Army University Biu": "NAUB",
  "Nigerian Defence Academy Kaduna": "NDA",
  "Nigerian Maritime University Okerenkoko, Delta State": "NMU",
  "Nigerian University of Technology and Management, Apapa, Lagos State": "NUTM",
  "Nile University of Nigeria, Abuja": "NUN",
  "Nnamdi Azikiwe University, Awka": "UNIZIK",
  "Obafemi Awolowo University, Ile-Ife": "OAU",
  "Oduduwa University, Ipetumodu, Osun State": "OUI",
  "Olabisi Onabanjo University, Ago Iwoye": "OOU",
  "Olusegun Agagu University of Science and Technology, Okitipupa": "OAUST",
  "Osun State College of Education, Ila-Orangun": "OSCOED ILA",
  "Osun State College of Education, Ilesa": "OSCOED",
  "Osun State College of Technology, Esa-Oke": "OSCOTECH",
  "Osun State Polytechnic, Iree": "OSPOLY",
  "Osun State University Osogbo": "UNIOSUN",
  "Oyo State College of Agriculture and Technology, Igbo-Ora": "OYSCATECH",
  "Pan-Atlantic University, Lagos": "PAU",
  "PeaceLand University, Enugu State": "PUE",
  "Precious Cornerstone University, Oyo": "PCU",
  "Prince Abubakar Audu University Anyigba": "PAAU",
  "Redeemer's University, Ede": "RUN",
  "Rivers State University": "RIVSU",
  "Rufus Giwa Polytechnic, Owo": "RUGIPO",
  "Sam Maris University, Ondo": "SMU",
  "Skyline University, Kano": "SUK",
  "Sokoto State University": "SSU",
  "Sule Lamido University, Kafin Hausa, Jigawa": "SLU",
  "Tai Solarin College of Education, Omu-Ijebu": "TASCE",
  "Tai Solarin Federal University of Education, Ijagun, Ijebu Ode": "TASFUED",
  "Taraba State University, Jalingo": "TSU",
  "The Oke-Ogun Polytechnic, Saki (TOPS)": "TOPS",
  "The Polytechnic, Ibadan": "POLY IBADAN",
  "University of Abuja, Gwagwalada": "UNIABUJA",
  "University of Benin": "UNIBEN",
  "University of Calabar": "UNICAL",
  "University of Cross River State, Calabar": "UNICROSS",
  "University of Delta, Agbor": "UNIDEL",
  "University of Ibadan": "UI",
  "University of Ilesa, Osun State": "UNILESA",
  "University of Ilorin": "UNILORIN",
  "University of Jos": "UNIJOS",
  "University of Lagos": "UNILAG",
  "University of Maiduguri": "UNIMAID",
  "University of Nigeria, Nsukka": "UNN",
  "University of Port-Harcourt": "UNIPORT",
  "University of Uyo": "UNIUYO",
  "Usmanu Danfodiyo University, Sokoto": "UDUS",
  "Western Delta University, Oghara Delta State": "WDU",
  "Yaba College of Technology, Yaba, Lagos": "YABATECH",
  "Yobe State University, Damaturu": "YSU",
  "Yusuf Maitama Sule Federal University of Education, Kano": "YMSFUEK",
  "Zamfara State University": "ZSU",
};
